window.PERFUMES = [
  {id:1,name:"Velvet Verse",inspired:"Poem",notes:["floral","powdery","musk"],desc:"Warm floral blend with soft powdery notes and a romantic aura."},
  {id:2,name:"Pure Snow Musk",inspired:"White Musk",notes:["musk","clean","fresh"],desc:"Clean, soft, airy musk with long-lasting freshness."},
  {id:3,name:"Midnight Dreamer",inspired:"Dream",notes:["fresh","sweet"],desc:"Smooth and lightly sweet with a calm, dreamy aura."},
  {id:4,name:"Soft Dove Mist",inspired:"Dove",notes:["fresh","creamy","musk"],desc:"Fresh, clean, creamy fragrance with a comforting soap-like touch."},
  {id:5,name:"Golden Talon",inspired:"Golden Hawk",notes:["woody","citrus"],desc:"Sharp citrus opening with masculine woody depth."},
  {id:6,name:"Midnight Charlie",inspired:"Charlie Black",notes:["spicy","woody"],desc:"Warm spicy masculine scent with aromatic undertones."},
  {id:7,name:"Rider’s Edge",inspired:"Harley Davidson",notes:["leather","woody","smoky"],desc:"Rugged leathery aroma with smoky, adventurous vibes."},
  {id:8,name:"Crystal Musk",inspired:"White Jovan Musk",notes:["musk","floral","clean"],desc:"Fresh musky aroma with a lightly floral clean finish."},
  {id:9,name:"Open Breeze",inspired:"Open",notes:["green","fresh"],desc:"Herbal green freshness with a cool aromatic finish."},
  {id:10,name:"Brute Force",inspired:"Brut",notes:["spicy","musk"],desc:"Classic barbershop fougère with spice and musk."},
  {id:11,name:"Snow Nevia",inspired:"Nevia",notes:["powdery","fresh","musk"],desc:"Fresh, creamy, soft fragrance with a soothing feel."},
  {id:12,name:"Royal Mirage Essence",inspired:"Royal Mirage",notes:["floral","powdery"],desc:"Powdery, floral, elegant, and long-lasting scent."},
  {id:13,name:"Solo Legend",inspired:"One Man Show",notes:["woody","aromatic"],desc:"Strong woody-aromatic with herbal sharpness."},
  {id:14,name:"Havoc Storm",inspired:"Havoc",notes:["fresh","sweet"],desc:"Mild sweet freshness with a youthful energetic vibe."},
  {id:15,name:"Urban Hugo",inspired:"Hugo",notes:["green","fresh","spicy"],desc:"Green, fresh, slightly spicy masculine scent."},
  {id:16,name:"Sweet Aura",inspired:"Sweet Heart",notes:["floral","musk","sweet"],desc:"Soft floral sweetness balanced with musk."},
  {id:17,name:"Mars Fire",inspired:"Mars",notes:["spicy","warm"],desc:"Spicy, warm, bold scent with strong projection."},
  {id:18,name:"Cobra Strike",inspired:"Cobra",notes:["spicy","sharp"],desc:"Sharp, spicy masculine scent with a punch."},
  {id:19,name:"Inferno Wood",inspired:"Fahrenheit",notes:["leather","woody","smoky"],desc:"Smoky leather blended with violet leaf & warm spice."},
  {id:20,name:"Ocean Attar Mist",inspired:"Sea Seven Attarful",notes:["aquatic","fresh"],desc:"Fresh aquatic scent with crisp salty waves."},
  {id:21,name:"Azure Seven",inspired:"Sea Seven",notes:["aquatic","fresh"],desc:"Pure oceanic freshness with an airy cool finish."},
  {id:22,name:"Fresh Ponds Mist",inspired:"Ponds",notes:["powdery","fresh","musk"],desc:"Clean, powdery, creamy freshness."},
  {id:23,name:"Blue Velvet Lady",inspired:"Blue Lady",notes:["floral","fruity","musk"],desc:"Floral-fruity feminine scent with soft sweetness."},
  {id:24,name:"Paso Legend",inspired:"El Paso",notes:["woody","spicy"],desc:"Woody spicy masculine fragrance with warm depth."},
  {id:25,name:"Kewda Bloom",inspired:"Kevda",notes:["floral","traditional"],desc:"Traditional fresh sweet floral attar."},
  {id:26,name:"Bold Belle",inspired:"Good Girl",notes:["sweet","floral","warm"],desc:"Sweet, sensual floral with warm tonka & cocoa."},
  {id:27,name:"Nice Breeze",inspired:"Nice",notes:["fresh","floral"],desc:"Simple fresh floral-aquatic with soft pleasant notes."},
  {id:28,name:"Lomani Noir",inspired:"Lomani",notes:["woody","aromatic"],desc:"Aromatic woody blend with citrus freshness."},
  {id:29,name:"Night Drakkar",inspired:"Drakkar Noir",notes:["spicy","aromatic"],desc:"Herbal spicy masculine fougère."},
  {id:30,name:"Aqua Wave",inspired:"Cool Water",notes:["aquatic","fresh","mint"],desc:"Fresh oceanic notes with mint & lavender."},
  {id:31,name:"Scarlet Charlie",inspired:"Charlie Red",notes:["floral","spicy"],desc:"Warm floral sweetness with spicy feminine tones."},
  {id:32,name:"Sport Breeze",inspired:"Polo Sport",notes:["citrus","fresh"],desc:"Clean sporty citrus with green notes."},
  {id:33,name:"Blue Charge",inspired:"Blue Challenge",notes:["fresh","blue"],desc:"Fresh blue aromatic masculine scent."},
  {id:34,name:"London Snow",inspired:"White London",notes:["citrus","fresh","musk"],desc:"Bright citrusy fragrance with soft musk."},
  {id:35,name:"Ocean Drift",inspired:"Cool Water",notes:["aquatic","fresh","mint"],desc:"Minty aquatic freshness with a calm coastal vibe."}
];
