<script>
window.PERFUMES = [
  {id:1,name:"Velvet Verse",inspired:"Poem",type:"floral",desc:"Warm floral blend with soft powdery notes and a romantic aura."},
  {id:2,name:"Pure Snow Musk",inspired:"White Musk",type:"musk",desc:"Clean, soft, airy musk with long-lasting freshness."},
  {id:3,name:"Midnight Dreamer",inspired:"Dream",type:"fresh",desc:"Smooth and lightly sweet with a calm, dreamy aura."},
  {id:4,name:"Soft Dove Mist",inspired:"Dove",type:"fresh",desc:"Fresh, clean, creamy fragrance with a comforting soap-like touch."},
  {id:5,name:"Golden Talon",inspired:"Golden Hawk",type:"woody",desc:"Sharp citrus opening with masculine woody depth."},
  {id:6,name:"Midnight Charlie",inspired:"Charlie Black",type:"spicy",desc:"Warm spicy masculine scent with aromatic undertones."},
  {id:7,name:"Rider’s Edge",inspired:"Harley Davidson",type:"woody",desc:"Rugged leathery aroma with smoky, adventurous vibes."},
  {id:8,name:"Crystal Musk",inspired:"White Jovan Musk",type:"musk",desc:"Fresh musky aroma with a lightly floral clean finish."},
  {id:9,name:"Open Breeze",inspired:"Open",type:"fresh",desc:"Herbal green freshness with a cool aromatic finish."},
  {id:10,name:"Brute Force",inspired:"Brut",type:"spicy",desc:"Classic barbershop fougère with spice and musk."},
  {id:11,name:"Snow Nevia",inspired:"Nevia",type:"fresh",desc:"Fresh, creamy, soft fragrance with a soothing feel."},
  {id:12,name:"Royal Mirage Essence",inspired:"Royal Mirage",type:"floral",desc:"Powdery, floral, elegant, and long-lasting scent."},
  {id:13,name:"Solo Legend",inspired:"One Man Show",type:"woody",desc:"Strong woody-aromatic with herbal sharpness."},
  {id:14,name:"Havoc Storm",inspired:"Havoc",type:"fresh",desc:"Mild sweet freshness with a youthful energetic vibe."},
  {id:15,name:"Urban Hugo",inspired:"Hugo",type:"fresh",desc:"Green, fresh, slightly spicy masculine scent."},
  {id:16,name:"Sweet Aura",inspired:"Sweet Heart",type:"floral",desc:"Soft floral sweetness balanced with musk."},
  {id:17,name:"Mars Fire",inspired:"Mars",type:"spicy",desc:"Spicy, warm, bold scent with strong projection."},
  {id:18,name:"Cobra Strike",inspired:"Cobra",type:"spicy",desc:"Sharp, spicy masculine scent with a punch."},
  {id:19,name:"Inferno Wood",inspired:"Fahrenheit",type:"woody",desc:"Smoky leather blended with violet leaf & warm spice."},
  {id:20,name:"Ocean Attar Mist",inspired:"Sea Seven Attarful",type:"fresh",desc:"Fresh aquatic scent with crisp salty waves."},
  {id:21,name:"Azure Seven",inspired:"Sea Seven",type:"fresh",desc:"Pure oceanic freshness with an airy cool finish."},
  {id:22,name:"Fresh Ponds Mist",inspired:"Ponds",type:"fresh",desc:"Clean, powdery, creamy freshness."},
  {id:23,name:"Blue Velvet Lady",inspired:"Blue Lady",type:"floral",desc:"Floral-fruity feminine scent with soft sweetness."},
  {id:24,name:"Paso Legend",inspired:"El Paso",type:"woody",desc:"Woody spicy masculine fragrance with warm depth."},
  {id:25,name:"Kewda Bloom",inspired:"Kevda",type:"floral",desc:"Traditional fresh sweet floral attar."},
  {id:26,name:"Bold Belle",inspired:"Good Girl",type:"floral",desc:"Sweet, sensual floral with warm tonka & cocoa."},
  {id:27,name:"Nice Breeze",inspired:"Nice",type:"fresh",desc:"Simple fresh floral-aquatic with soft pleasant notes."},
  {id:28,name:"Lomani Noir",inspired:"Lomani",type:"woody",desc:"Aromatic woody blend with citrus freshness."},
  {id:29,name:"Night Drakkar",inspired:"Drakkar Noir",type:"spicy",desc:"Herbal spicy masculine fougère."},
  {id:30,name:"Aqua Wave",inspired:"Cool Water",type:"fresh",desc:"Fresh oceanic notes with mint & lavender."},
  {id:31,name:"Scarlet Charlie",inspired:"Charlie Red",type:"floral",desc:"Warm floral sweetness with spicy feminine tones."},
  {id:32,name:"Sport Breeze",inspired:"Polo Sport",type:"fresh",desc:"Clean sporty citrus with green notes."},
  {id:33,name:"Blue Charge",inspired:"Blue Challenge",type:"fresh",desc:"Fresh blue aromatic masculine scent."},
  {id:34,name:"London Snow",inspired:"White London",type:"fresh",desc:"Bright citrusy fragrance with soft musk."},
  {id:35,name:"Ocean Drift",inspired:"Cool Water",type:"fresh",desc:"Minty aquatic freshness with a calm coastal vibe."}
];
</script>
